---
# tasks file for dns

- name: Install bind9
  apt:
    name: bind9
    state: present

- name: Install dnsutils
  apt:
    name: dnsutils
    state: present

- name: Copy named.conf
  template:
    src: named.conf
    dest: /etc/bind/named.conf

- name: Remove unneeded config files
  file:
    path: /etc/bind/{{ item }}
    state: absent
  with_items:
    - bind.keys
    - db.0
    - db.127
    - db.255
    - db.empty
    - db.local
    - named.conf.default-zones
    - named.conf.local
    - named.conf.options
    - rndc.key
    - zones.rfc1918

- name: Ensure the /etc/bind/zones directory exists
  file:
    path: /etc/bind/zones
    state: directory

- name: Copy zones
  template:
    src: "zones/{{ item }}"
    dest: "/etc/bind/zones/{{ item }}"
  with_items:
    - db.thenet.com
    - db.paste.go
    - db.progress.go
    - db.chat.go

- name: Restart bind9
  service: state=restarted name=bind9
