---
# tasks file for dns

- name: Install bind9
  apt:
    name: bind9
    state: present

- name: Install dnsutils
  apt:
    name: dnsutils
    state: present

- name: Copy named.conf.local
  template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local

- name: Ensure the /etc/bind/zones directory exists
  file:
    path: /etc/bind/zones
    state: directory

- name: Copy zones
  template:
    src: "zones/{{ item }}"
    dest: "/etc/bind/zones/{{ item }}"
  with_items:
    - db.thenet.com

- name: Restart bind9
  service: state=restarted name=bind9
