---
# tasks file for web

- name: Install nginx
  apt: name=nginx state=present

- name: Removing default configuration
  file: state=absent path=/etc/nginx/conf.d/default.conf

- name: Ensure sites-enabled is there
  file: state=directory path=/etc/nginx/sites-enabled
- name: Ensure sites-available is there
  file: state=directory path=/etc/nginx/sites-available

- name: Adding Nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Restart nginx
  service: state=restarted name=nginx
