---
# tasks file for web

- name: Install nginx
  apt: name=nginx state=present

- name: Removing default configuration
  file: state=absent path=/etc/nginx/conf.d/default.conf
- name: Removing default configuration
  file: state=absent path=/etc/nginx/sites-enabled/default
- name: Removing default configuration
  file: state=absent path=/etc/nginx/sites-available/default

- name: Ensure sites-enabled is there
  file: state=directory path=/etc/nginx/sites-enabled
- name: Ensure sites-available is there
  file: state=directory path=/etc/nginx/sites-available
- name: Ensure www is there
  file: state=directory path=/var/www

- name: Adding Nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

# App folders
- name: Ensure thenet.com is there
  file: state=directory path=/var/www/thenet.com
- name: Ensure paste.go is there
  file: state=directory path=/var/www/paste.go
- name: Ensure chat.go is there
  file: state=directory path=/var/www/chat.go

# thenet.com
- name: Copy thenet.com html
  template:
    src: index.html
    dest: /var/www/thenet.com/index.html
- name: Copy Nginx Config
  template:
    src: thenet.com.conf
    dest: /etc/nginx/sites-available/000_default.conf
- name: Link Nginx Config
  file:
    state: link
    src: /etc/nginx/sites-available/000_default.conf
    dest: /etc/nginx/sites-enabled/000_default.conf

# Install node
- name: Add node repository key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
- name: Add node respository
  apt_repository: mode=644 repo='deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main' state=present update_cache=yes
- name: Install node
  apt: name=nodejs state=latest
- name: Install npm
  apt: name=npm state=latest

# paste.go
- name: Extract haste-server-master.zip
  unarchive:
    src: ../files/haste-server-master.zip
    dest: /var/www/paste.go
- name: Install packages based on package.json
  npm:
    path: /var/www/paste.go/haste-server-master
    state: present
- name: Install packages based on package.json
  npm:
    name: memcached
    path: /var/www/paste.go/haste-server-master
- name: Copy Config
  template:
    src: paste-config.json
    dest: /var/www/paste.go/haste-server-master/config.js
- name: Copy service
  template:
    src: paste-go.service
    dest: /etc/systemd/system/paste-go.service
- name: Restart service
  service:
    name: paste-go
    state: restarted
    enabled: yes
- name: Copy Nginx Config
  template:
    src: paste.go.conf
    dest: /etc/nginx/sites-available/paste.go.conf
- name: Link Nginx Config
  file:
    state: link
    src: /etc/nginx/sites-available/paste.go.conf
    dest: /etc/nginx/sites-enabled/paste.go.conf

# chat.go
- name: Extract node-chat-master.zip
  unarchive:
    src: ../files/node-chat-master.zip
    dest: /var/www/chat.go
- name: Install packages based on package.json
  npm:
    path: /var/www/chat.go/node-chat-master
    state: present
- name: Copy Config
  template:
    src: chat-config.json
    dest: /var/www/paste.go/node-chat-master/config.json
- name: Copy service
  template:
    src: chat-go.service
    dest: /etc/systemd/system/chat-go.service
- name: Restart service
  service:
    name: chat-go
    state: restarted
    enabled: yes
- name: Copy Nginx Config
  template:
    src: chat.go.conf
    dest: /etc/nginx/sites-available/chat.go.conf
- name: Link Nginx Config
  file:
    state: link
    src: /etc/nginx/sites-available/chat.go.conf
    dest: /etc/nginx/sites-enabled/chat.go.conf

- name: Restart nginx
  service: state=restarted name=nginx
